version: "3.9"
services:
  nodevnc:
    build:
      context: .
      args:
        - vncpasswd=forabozo
        - username=guest
    environment:
      - APP_USER=guest
    restart: always
    ports:
      - 5901:5901
      - 3000:3000
    volumes:
     - myapp:/home/guest/
volumes:
  myapp:
