version: "3.9"
services:
  nodevnc:
    container_name: zap
    build:
      context: .
      args:
        - vncpasswd=forabozo
        - username=guest
    environment:
      - APP_USER=guest
      - REDIS_URL=redis://192.168.0.7:6379
      - TZ=America/Sao_Paulo
      - GOOD_MORNING_CRON=0 8 * * *
      - GOOD_EVENING_CRON=0 18 * * *
    restart: always
    ports:
      - 5901:5901
      - 3002:3002
    volumes:
      - userdata:/tmp/whatsapp_userdata
volumes:
  userdata:
