version: "3.9"
services:
  nodevnc:
    build:
      context: .
      args:
        - vncpasswd=forabozo
        - username=guest
    environment:
      - APP_USER=guest
      - REDIS_URL=redis://192.168.0.7:6379
    restart: always
    ports:
      - 5901:5901
      - 3000:3000
